package com.rajantech;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-07-03T16:02:25.182+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://rajantech.com", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://rajantech.com/InputSOATest")
    @WebResult(name = "outputSOATest", targetNamespace = "http://rajantech.com", partName = "out")
    public OutputSOATest soaTest(
        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://rajantech.com")
        InputSOATest in
    );

    @WebMethod(operationName = "SOATest2")
    @WebResult(name = "outputSOATest", targetNamespace = "http://rajantech.com", partName = "out")
    public OutputSOATest soaTest2(
        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://rajantech.com")
        InputSOATest in
    );
}
